### ISSUE TITLE
TestPorts_VLANs E2E test failed

### ISSUE THREAD

**Issue by displague** [StackPointCloud/packet-cli#387]
One E2E test failed:
```
=== RUN   TestPorts_VLANs
Error when calling `DevicesApi.FindDeviceById`: 403 Forbidden
    helper.go:302: 403 Forbidden
    helper.go:305: Timeout while waiting for device: 467ae367-bb48-469d-b910-8e71533cf42f to be active
Error when calling `DevicesApi.FindDeviceById`: 403 Forbidden
    helper.go:310: 403 Forbidden
--- FAIL: TestPorts_VLANs (65.85s)
panic: runtime error: index out of range [2] with length 0 [recovered]
	panic: runtime error: index out of range [2] with length 0

goroutine 36 [running]:
testing.tRunner.func1.2({0xca9f80, 0xc0001cb338})
	/opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1399 +0x39f
panic({0xca9f80, 0xc0001cb338})
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:884 +0x212
github.com/equinix/metal-cli/test/e2e/ports.TestPorts_VLANs(0xc0004f4000)
	/home/runner/work/metal-cli/metal-cli/test/e2e/ports/vlans_test.go:28 +0x4dc
testing.tRunner(0xc0004f4000, 0xd6b4f0)
	/opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.13/x64/src/testing/testing.go:1493 +0x35f
FAIL	github.com/equinix/metal-cli/test/e2e/ports	596.680s
```

_Originally posted by @displague in https://github.com/equinix/metal-cli/issues/355#issuecomment-1804428216_

**Comment by aayushrangwala** [comment]
Also in the latest test run https://github.com/equinix/metal-cli/actions/runs/6932109723/job/18860656801?pr=376

This specific test is passing
```
=== RUN   TestPorts_VLANs
=== RUN   TestPorts_VLANs/vlan_assignment_port
--- PASS: TestPorts_VLANs (223.85s)
    --- PASS: TestPorts_VLANs/vlan_assignment_port (15.80s)
PASS
```

**Comment by aayushrangwala** [comment]
@displague we can close this issue
